cedar-policy/cedar-go

- go.mod
*Issue #, if available:* https://github.com/cedar-policy/cedar-go/issues/17
*Description of changes:* Sets Go 1.22 as the minimum Go version.
> Set Go 1.22 as min Go version

- .github/workflows/corpus.yml
- integration_tests/corpus_test.go
Issue #, if available: None
Description of changes:
This PR causes the Github action to fail correctly when the corpus tests have failed such that our alerting will actually be invoked.
I've also pulled in the fixes from https://github.com/cedar-policy/cedar-go/pull/16 so that the tests now pass.
I'd like to make additional changes to get these to run on every PR and to check in a copy of the tests to this repo and change the alerting to let us know when the tests are out of sync with the upstream version, but I'll save those for later. This at least gets us back to status quo.
> Fix up nightly corpus tests

- policy.go
- policy_test.go
Technically, this is a breaking change and will require us to go to 0.3.0.
> cedar: change JSON marshaling of the Position struct to use conventional lower case keys

- .github/workflows/corpus.yml
* Only run this workflow on the official cedar-go repo
* Update `actions/github-script` to @v7 to avoid warnings about using an old NodeJS version
* Only open an issue if the compare step failed. We don't necessarily want to open an issue if the `curl` fails for some reason.
* Give the job permission to create issues
* Only open an issue if an open one does not already exist
> Several improvements to the upstream corpus test workflow

- internal/parser/cedar_tokenize.go
- internal/parser/cedar_tokenize_test.go
- internal/parser/cedar_unmarshal.go
- internal/parser/cedar_unmarshal_test.go
This PR modifies the Cedar tokenizer to properly reserve the set of [reserved keywords](https://arc.net/l/quote/yvyhkfvf) from the Cedar spec. In addition, it resolves a parsing ambiguity for the `Primary` production, which requires a lookahead to determine whether it will be a `VAR`, `Entity`, or `ExtFun`.
> Fix parsing of reserved keywords

- README.md
- authorize_test.go
- internal/consts/consts.go
- internal/eval/comparable.go
- internal/eval/convert.go
- internal/eval/convert_test.go
- internal/eval/evalers.go
- internal/eval/evalers_test.go
- internal/eval/util.go
- internal/eval/util_test.go
- internal/extensions/extensions.go
- internal/extensions/extensions_test.go
- internal/json/json.go
- types/datetime.go
- types/datetime_test.go
- types/duration.go
- types/duration_test.go
- types/json.go
- types/json_test.go
- types/long.go
- types/long_test.go
- types/value.go
- types/value_test.go
- types/virtual.go
See merged [RFC 80](https://github.com/cedar-policy/rfcs/pull/80).
This PR adds:
- The `datetime` and `duration` type specified in [RFC 80](https://github.com/cedar-policy/rfcs/pull/80)
- Associated methods for those types
- An implementation of operator overloading for `ComparableValue`s, such as Long, Datetime, Duration.
This does not extend ComparableValue to Decimal, as there's no RFC / specification to make that so (doing so would be straightforward, however).
Both `datetime` and `duration` are backed by an int64 and can be lifted from a Go `time.Time` and a `time.Duration` respectively. It would be possible to remove the struct wrapper around the int64, as no other state is stored. We aren't doing this to prevent accidental casting / type assertions that remove the semantic meaning …
> Add the extension types, datetime and duration

- internal/json/json.go
- internal/json/json_marshal.go
- internal/json/json_unmarshal.go
- types/boolean.go
- types/datetime.go
- types/datetime_test.go
- types/decimal.go
- types/duration.go
- types/duration_test.go
- types/entities.go
- types/entities_test.go
- types/entity_uid.go
- types/ipaddr.go
- types/json_test.go
- types/long.go
- types/record.go
- types/set.go
- types/set_internal_test.go
- types/string.go
- types/value.go
Entities and extension functions have both an "implict" and "explict" form of JSON serialization, where the "implicit" form is only valid if the serialized data can be unambiguously determined to be of a given type. This can happen positionally (e.g. EntityUIDs in the serialization of the Entities object) or via knowledge gleaned from a schema (which we don't yet support).
It's _always_ safe to encode an entity or extension function via the "explicit" form, so let's make that the default. This also alleviates the types that don't have implicit and explicit forms from having to implement `ExplicitMarshalJSON()`.
With this approach, callers who know that it's safe to use the implicit form can do so and everyone else will get the safe …
> Invert the special casing of JSON marshaling for Value

- authorize.go
- internal/eval/compile.go
- internal/eval/compile_test.go
- internal/eval/convert_test.go
- internal/eval/evalers.go
- internal/eval/evalers_test.go
- internal/eval/fold.go
- internal/eval/partial.go
- internal/eval/partial_test.go
- x/exp/batch/batch.go
We don't currently have a benchmark that's telling us that we need this cache. In fact, several of our benchmarks show that for large, shallow entity graphs, the inCache actually slows down authorizations and batch evaluations because of all the extra allocation that goes on to build the map.
For deep entity graphs, such a cache might be useful, but I think instead that we'll try to put such a cache in the entity graph itself by keeping track of the transitive closure of every entity's parents. That way, the cache will be effective across multiple authorizations.
> internal/eval: remove the inCache

- README.md
https://github.com/cedar-policy/cedar-go/issues/14
Adds pkg.go.dev documentation badge to readme.
> Adds pkg.go.dev badge to readme

- internal/ast/ast_test.go
- internal/eval/compile.go
- internal/eval/compile_test.go
- internal/eval/convert_test.go
- internal/eval/evalers.go
- internal/eval/evalers_test.go
- internal/eval/fold_test.go
- internal/eval/partial_test.go
- internal/eval/util_test.go
- types.go
- types/json_test.go
- types/set.go
- types/set_internal_test.go
- types/set_test.go
- x/exp/batch/batch.go
- x/exp/batch/batch_test.go
In addition to making the two functions have a similar shape, this also cuts down quite a bit on the annoying `[]types.Value{}` wrapper detritus that we have to put around literal arguments.
> types: change Set() to take variadic arguments to match EntityUIDSet()

- authorize_test.go
- corpus_test.go
- internal/eval/evalers.go
- internal/eval/partial.go
- types.go
- types/entity_map.go
*Description of changes:* See title
Also, rename `cedar.Entities` to `cedar.EntityMap` to match the new name in the `types` package.
> types: remove the EntityMap.Load() method and use `[]` instead

- ast/ast_test.go
- ast/operator.go
- ast/value.go
- internal/ast/ast_test.go
- internal/ast/operator.go
- internal/ast/value.go
- internal/extensions/extensions.go
*Description of changes:* Add missing AST builder methods for datetime and duration literals as well as their associated methods.
> ast: Add AST builder methods for datetime-related types and operators

- ast/ast_test.go
- ast/value.go
Resolves #54
This change adds support for specifically calling extension functions in the AST package.
> Expose extension function calls in AST package

- types/datetime.go
- types/datetime_test.go
- types/decimal.go
- types/decimal_test.go
- types/duration.go
- types/duration_test.go
- types/ipaddr.go
- types/ipaddr_test.go
- types/json.go
- types/json_test.go
Create a generic `unmarshalExtensionValue()` helper function that supports all three forms of extension value JSON encoding:
* Explicit: `{ "__extn": { "fn": "decimal", "arg": "1234.5678" } }`
* Implicit object: `{ "fn": "decimal", "arg": "1234.5678" } }`
* Implicit string: `"1234.5678"`
Use it to flesh out the implementations of `UnmarshalJSON` for `IPAddr` and `Decimal`. Note that the implicit decoding will never actually be invoked until we have schema-driven decoding for entities.
> types: clean up JSON unmarshaling story for extension types

- .golangci.yml
- corpus_test.go
- internal/eval/partial_test.go
- internal/json/json_marshal.go
*Description of changes:* See title
> enable errcheck for the project and fix the violations discovered

- README.md
- authorize.go
- internal/eval/evalers.go
- internal/eval/partial.go
- types/entity_map.go
- types/entity_map_test.go
This changes the `PolicySet` `IsAuthorized()` method to take an `EntityGetter` interface instead of a concrete `EntityMap` instance, allowing alternative entity getter implementations to be passed to the authorization.
> IDX-470: Change PolicySet.IsAuthorized to take an EntityGetter interface in place of an EntityMap

- corpus_test.go
- x/exp/batch/batch.go
- x/exp/batch/batch_test.go
This PR changes two things:
- Makes the error handling for context errors more consistent, it will return an error if you cancel in the last batch request.
- Adds an error to the batch callback signature.  Any error will cause the batch processing to cease and the error to be returned.
> Improve batch error handling

- types.go
- x/exp/batch/batch.go
- x/exp/batch/batch_test.go
This changes the x/exp/batch package's `Authorize()` to take an `EntityGetter` interface in place of a concrete `EntityMap`, to align this with the `PolicySet.IsAuthorized()` signature.
> Change batch Authorize() to take an EntityGetter in place of an EntityMap

- types/datetime.go
- types/datetime_test.go
The Go time package will silently ignore dates that don't exist on the calendar, instead carrying forward the erroneous time component. As an example, `2024-02-30` will become `2024-03-01`, since there was no February 30th, in 2024 (or ever).
This change returns an error when there's a discrepancy between the numbers we parse from the string, and the component after creating a Go time.Time value from the parsed numbers.
*Issue https://github.com/cedar-policy/rfcs/issues/94*
> Addresses cedar-policy/rfcs#94 concerns about time wrapping

- README.md
*Description of changes:* Removes the broken `golangci-lint` badge from the README.
> cedar-go: remove golangci-lint badge from README.md

- README.md
*Description of changes:* Use `cedar.Authorize` instead of PolicySet's `IsAuthorized` method in ReadMe.md example
> minor: use `cedar.Authorize`  in ReadMe.md example

- README.md
- types/entity.go
- types/entity_test.go
Having an implementation of Equal() adds a canonical method of checking for Entity equality and makes it compatible with the cmp package's [Equal()](https://pkg.go.dev/github.com/google/go-cmp/cmp#Equal) function and other types in this package (e.g. Record, EntityUID).
> types: add Entity.Equal() implementation

- .golangci.yml
Addresses #94
A change in the linters is blocking a contributor's PR.
> cedar-go: ignore var-naming revive lint errors in the types package

- internal/eval/compile.go
- internal/eval/convert.go
- internal/eval/convert_test.go
- x/exp/eval/eval.go
- x/exp/eval/eval_test.go
> expose Eval function for  custom partial eval
